run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - errcheck
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
    # Fail if tabs are used
    tab_width: 0  # Optional; gofmt defaults to 8, but Go always formats using tabs unless forced
